# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bacb9f23e3d43edf9dd6af536fd128ed4f0b6d448350b5d05c2157d0d06c337aff548d9059c3664bd9768864584a93ce730190c2083a9f96b9ffebf64090014e

test:
  secret_key_base: 27536bdd68e5c7f77be4b2732a0b2177c53aa015ca96f1c10a2f43ad6afdd93beb5fbe900e4f8940342ccb285d552aa0ae0c0ce08ee34d3aa4378e73d397dffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
